### ISSUE TITLE
Registration Page [Sad / Edge cases]

### ISSUE THREAD

**Issue by b-enji-cmd** [b-enji-cmd/viewing_party#20]
- [x] Passwords don't match 
- [x] Email is already registered

**Comment by Diana20920** [comment]
**Promising References:**
- ["Confirmation checks 2 text fields for the same input and will not save it if they do not match up."](https://medium.com/@lilimae/the-fundamentals-of-validations-in-ruby-activerecord-93b11358f27f)
- Even a better one, and it looks like we will need to add back the `:password_confirmation` to strong params [stackoverflow question](https://stackoverflow.com/questions/44530504/password-confirmation-in-rails-5)
